#!/bin/sh

RESETBTN_ARGS=""
RESETBTN_PID_FILE=/var/run/resetbtn.pid

start() {
  printf "Starting the reset button actions daemon: "
  umask 077
  start-stop-daemon -b -m -S -q -p $RESETBTN_PID_FILE \
    --exec /usr/sbin/reset_button.sh -- $RESETBTN_ARGS
  [ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
  printf "Stopping the reset button actions daemon: "
  start-stop-daemon -K -q -p $RESETBTN_PID_FILE
  [ $? = 0 ] && echo "OK" || echo "FAIL"
}

restart() {
  stop
  start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart | reload)
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit $?
